### ISSUE TITLE
How to debug extension in chrome without minifying code

### ISSUE THREAD

**Issue by caddac** [int128/new-tab-bookmarks#4]
Hello,

I pulled down the repository and am trying to debug it in Chrome. How can I debug the code without minifying it before?

**Comment by int128** [comment]
Remove following line to turn off minifying.

https://github.com/int128/new-tab-bookmarks/blob/master/gulpfile.js#L30
```javascript
    .pipe(uglify())
```

Thanks.

**Comment by int128** [comment]
I updated build system and now we can debug the code by `npm start`.
